spring.datasource.url=jdbc:mysql://localhost:3306/Demo
spring.datasource.username=root
spring.datasource.password=


spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.thymeleaf.enabled=true

# SMTP server host
spring.mail.host=sandbox.smtp.mailtrap.io

# SMTP server port
spring.mail.port=2525

# SMTP username
spring.mail.username=70a2ef04028978

# SMTP password
spring.mail.password=6c307b5aa4963f

# Enable TLS
spring.mail.properties.mail.smtp.starttls.enable=true

# Enable SSL (if needed)
# spring.mail.properties.mail.smtp.ssl.enable=true



